/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STLEN_H_RPCGEN
#define _STLEN_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define STRLEN ((rpc_uint)117)
#define STRLENVERS ((rpc_uint)1)

#ifdef __cplusplus
#define strlen ((rpc_uint)1)
extern "C" int * strlen_1(char **, CLIENT *);
extern "C" int * strlen_1_svc(char **, struct svc_req *);

#elif __STDC__
#define strlen ((rpc_uint)1)
extern  int * strlen_1(char **, CLIENT *);
extern  int * strlen_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define strlen ((rpc_uint)1)
extern  int * strlen_1();
extern  int * strlen_1_svc();
#endif /* Old Style C */

#endif /* !_STLEN_H_RPCGEN */
