package ag.ifpb.rmi.iiop.idl.service;


/**
* ag/ifpb/rmi/iiop/idl/service/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, March 28, 2018 2:34:08 AM BRT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
