package ag.ifpb.rmi.iiop.idl.service;


/**
* ag/ifpb/rmi/iiop/idl/service/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, March 28, 2018 2:34:08 AM BRT
*/

public interface HelloOperations 
{
  void hello (String name);
} // interface HelloOperations
